<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ECommerce.Catalog.Domain\ECommerce.Catalog.Domain.csproj" />
    <ProjectReference Include="..\ECommerce.Catalog.Contracts\ECommerce.Catalog.Contracts.csproj" />
    <ProjectReference Include="..\..\..\Shared\ECommerce.Shared.Kernel\ECommerce.Shared.Kernel.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Promotion\ECommerce.Promotion.Contracts\ECommerce.Promotion.Contracts.csproj" />
  </ItemGroup>

</Project>
